- id: '1775595766007'
  alias: Hobby room wall switch -> hobby room light
  description: Control Hobby room light from Shelly wall switch input state
  triggers:
  - topic: shelly1g4-ccba97c89350/status/input:0
    trigger: mqtt
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.state == true }}'
      sequence:
      - target:
          entity_id: light.hobby_room_light_ceiling
        action: light.turn_on
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.state == false }}'
      sequence:
      - target:
          entity_id: light.hobby_room_light_ceiling
        action: light.turn_off
  mode: restart
- id: '1775687797974'
  alias: Closet wall switch -> closet light
  description: Control closet light from Shelly wall switch input state
  triggers:
  - topic: shelly1g4-ccba97c8a17c/status/input:0
    trigger: mqtt
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.state == true }}'
      sequence:
      - target:
          entity_id: light.closet_light_ceiling
        action: light.turn_off
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.state == false }}'
      sequence:
      - target:
          entity_id: light.closet_light_ceiling
        action: light.turn_on
  mode: restart
- id: '1775738182218'
  alias: Bedroom wall switch -> Bedroom lights
  description: Control Bedroom lights group from Shelly wall switch input state
  triggers:
  - topic: shelly1g4-ccba97c888c8/status/input:0
    trigger: mqtt
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.state == true }}'
      sequence:
      - target:
          entity_id: light.bedroom_lights
        action: light.turn_on
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.state == false }}'
      sequence:
      - target:
          entity_id: light.bedroom_lights
        action: light.turn_off
  mode: restart
- id: '1775740822511'
  alias: Kitchen wall switch -> Kitchen lights
  description: Control Kitchen lights group from Shelly wall switch input state
  triggers:
  - topic: shelly1g4-a085e3bd891c/status/input:0
    trigger: mqtt
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.state == true }}'
      sequence:
      - target:
          entity_id: light.kitchen_lights
        action: light.turn_on
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.state == false }}'
      sequence:
      - target:
          entity_id: light.kitchen_lights
        action: light.turn_off
  mode: restart
- id: living_room_spotlight_wall_switch
  alias: Living room wall switch -> Living room spotlight
  description: Control Living room spotlight from Shelly wall switch input state
  triggers:
  - topic: shelly1g4-a085e3bcdf24/status/input:0
    trigger: mqtt
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.state == true }}'
      sequence:
      - target:
          entity_id: light.living_room_light_spotlight
        action: light.turn_on
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.state == false }}'
      sequence:
      - target:
          entity_id: light.living_room_light_spotlight
        action: light.turn_off
  mode: restart
- id: corridor_wall_switch_toggle
  alias: Corridor wall switch -> Corridor lights toggle
  description: Toggle corridor lights from Shelly wall switch state change
  triggers:
  - topic: shelly1pmg4-a085e3bc7c48/status/input:0
    trigger: mqtt
  conditions: []
  actions:
  - target:
      entity_id:
      - light.corridor_light_spotlight
      - light.corridor_light_2
      - light.corridor_light_3
    action: light.toggle
  mode: restart
