# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  switch:
    - name: "Hobby room ceiling light power"
      unique_id: "switch_hobby_room_light_ceiling_power"
      command_topic: "shelly1g4-ccba97c89350/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-ccba97c89350/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-ccba97c89350/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Closet light ceiling power"
      unique_id: "switch_closet_light_ceiling_power"
      command_topic: "shelly1g4-ccba97c8a17c/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-ccba97c8a17c/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-ccba97c8a17c/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Bedroom light ceiling power"
      unique_id: "switch_bedroom_light_ceiling_power"
      command_topic: "shelly1g4-ccba97c888c8/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-ccba97c888c8/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-ccba97c888c8/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Kitchen light ceiling power"
      unique_id: "switch_kitchen_light_ceiling_power"
      command_topic: "shelly1g4-a085e3bd891c/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-a085e3bd891c/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-a085e3bd891c/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Kitchen light desk power"
      unique_id: "switch_kitchen_light_desk_power"
      command_topic: "shelly1pmg4-a085e3bcfb14/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1pmg4-a085e3bcfb14/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1pmg4-a085e3bcfb14/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Kitchen light breakfast cabinet power"
      unique_id: "switch_kitchen_light_breakfast_cabinet_power"
      command_topic: "shelly1g4-ccba97c89b84/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-ccba97c89b84/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-ccba97c89b84/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Living room spotlight power"
      unique_id: "switch_living_room_light_spotlight_power"
      command_topic: "shelly1g4-a085e3bcdf24/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-a085e3bcdf24/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-a085e3bcdf24/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Living room window light power"
      unique_id: "switch_living_room_light_window_power"
      command_topic: "shelly1g4-a085e3c16eec/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-a085e3c16eec/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-a085e3c16eec/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Living room ceiling light power"
      unique_id: "switch_living_room_light_ceiling_power"
      command_topic: "shelly1g4-ccba97c89790/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-ccba97c89790/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-ccba97c89790/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Corridor light group power"
      unique_id: "switch_corridor_light_group_power"
      command_topic: "shelly1pmg4-a085e3bc7c48/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1pmg4-a085e3bc7c48/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1pmg4-a085e3bc7c48/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Hall light ceiling power"
      unique_id: "switch_hall_light_ceiling_power"
      command_topic: "shelly1pmg4-a085e3bd0210/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1pmg4-a085e3bd0210/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1pmg4-a085e3bd0210/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Front yard light power"
      unique_id: "switch_front_yard_light_power"
      command_topic: "shelly1pmg4-a085e3bbd280/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1pmg4-a085e3bbd280/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1pmg4-a085e3bbd280/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "WC light ceiling power"
      unique_id: "switch_wc_light_ceiling_power"
      command_topic: "shelly1g4-a085e3bd81e4/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-a085e3bd81e4/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-a085e3bd81e4/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Office light ceiling power"
      unique_id: "switch_office_light_ceiling_power"
      command_topic: "shelly1g4-ccba97c8968c/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-ccba97c8968c/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-ccba97c8968c/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Laundry room light ceiling power"
      unique_id: "switch_laundry_room_light_ceiling_power"
      command_topic: "shelly1g4-a085e3bd8af0/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-a085e3bd8af0/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-a085e3bd8af0/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Bathroom ceiling light"
      unique_id: "switch_bathroom_light_ceiling_power"
      command_topic: "shelly1g4-ccba97c8cbf8/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-ccba97c8cbf8/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-ccba97c8cbf8/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Bathroom mirror light"
      unique_id: "switch_bathroom_light_mirror_power"
      command_topic: "shelly1g4-a085e3bcd118/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-a085e3bcd118/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-a085e3bcd118/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Sauna bench light"
      unique_id: "switch_sauna_light_bench_power"
      command_topic: "shelly1g4-ccba97c8a044/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-ccba97c8a044/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-ccba97c8a044/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Sauna wall light"
      unique_id: "switch_sauna_light_wall_power"
      command_topic: "shelly1g4-ccba97c89804/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-ccba97c89804/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-ccba97c89804/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Back yard lights living room"
      unique_id: "switch_back_yard_light_living_room_power"
      command_topic: "shelly1g4-ccba97c8856c/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-ccba97c8856c/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-ccba97c8856c/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Back yard lights laundry room"
      unique_id: "switch_back_yard_light_laundry_room_power"
      command_topic: "shelly1g4-a085e3c16c94/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-a085e3c16c94/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-a085e3c16c94/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Warehouse light ceiling"
      unique_id: "switch_warehouse_light_ceiling_power"
      command_topic: "shelly1pmg4-a085e3bbb77c/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1pmg4-a085e3bbb77c/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1pmg4-a085e3bbb77c/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Attic light ceiling"
      unique_id: "switch_attic_light_ceiling_power"
      command_topic: "shelly1g4-a085e3c197b0/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-a085e3c197b0/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-a085e3c197b0/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0

    - name: "Technical room light ceiling power"
      unique_id: "switch_technical_room_light_ceiling_power"
      command_topic: "shelly1g4-a085e3bd87d0/rpc"
      command_template: >-
        {% if value == 'ON' %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":true}}{% else %}{"id":1,"src":"ha","method":"Switch.Set","params":{"id":0,"on":false}}{% endif %}
      state_topic: "shelly1g4-a085e3bd87d0/status/switch:0"
      value_template: "{{ 'ON' if value_json.output == true else 'OFF' if value_json.output == false else '' }}"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      availability_topic: "shelly1g4-a085e3bd87d0/online"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0
